name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - "Docs/*"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master

permissions:
  actions: read
  contents: write
  issues: read
  checks: write
  pull-requests: write

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
        - name: Windows
          tag: windows-latest
        - name: macOS
          tag: macos-latest
        - name: Ubuntu
          tag: ubuntu-latest
        jdk:
        - name: JDK 11
          version: '11'
    name: CI (${{ matrix.os.name }} - ${{ matrix.jdk.name }})
    if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ${{ matrix.os.tag }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup ${{ matrix.jdk.name }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin # Eclipse Temurin
        java-version: ${{ matrix.jdk.version }}
        cache: 'maven'
    - name: Run Maven Install
      run: |
        mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V "$@"
      shell: bash
    - name: Run Test
      run: |
        mvn test -B "$@"
      shell: bash
    - name: Publish Test Results
      if: ${{ always() }}
      uses: mikepenz/action-junit-report@v4
      with:
        require_tests: true
        fail_on_failure: true
        report_paths: "**/TEST-*.xml"
        exclude_sources: target/
        check_name: Test Results - ${{ matrix.os.name }} (${{ matrix.jdk.name }})
